### ISSUE TITLE
目录页字体大小和排版

### ISSUE THREAD

**Issue by li-Yongpeng** [wurahara/SEU-master-thesis#11]
请问在哪里可以修改目录页的字体大小？
现有的目录页面字体太大，会导致目录所占页面过多。
![image](https://user-images.githubusercontent.com/72585755/158760708-ea27051a-4a8a-4453-a7ed-8d95ee59b7ed.png)

**Comment by higuoxing** [comment]
可以在 `main.tex` 中的 `\tableofcontents` 命令前使用下面的命令修改字体。

```
\renewcommand{\cftpartfont}{<desired font>}       % \part font in ToC
\renewcommand{\cftchapfont}{<desired font>}       % \chapter font in ToC
\renewcommand{\cftsecfont}{<desired font>}        % \section font in ToC
\renewcommand{\cftsubsecfont}{<desired font>}     % \subsection font in ToC
\renewcommand{\cftsubsubsecfont}{<desired font>}  % \subsubsection font in ToC
```

参考：https://stackoverflow.com/questions/47604626/how-to-customise-font-size-of-table-of-contents-generated-by-packagetocloft-in

**Comment by li-Yongpeng** [comment]
感谢，还可以通过以下选项调整字间距
`\setlength{\cftbeforesecskip}{2pt}
\setlength{\cftbeforechapskip}{2pt}
\setlength{\cftaftertoctitleskip}{2pt}`
