### ISSUE TITLE
尾页封面以及首页标题的问题

### ISSUE THREAD

**Issue by jhhuang96** [wurahara/SEU-master-thesis#3]
问题1：
在main.tex注释掉\makebigcover会差生尾页的logo图案偏离。
![图片](https://user-images.githubusercontent.com/17799955/111054885-0d290c00-84ab-11eb-9ce5-5d96834bc517.png)

问题2：
首页的大标题如果只有1行时，必须要修改注释cls的497行-498行代码：
```
            \erhao\heiti\@title %\\ 
            % \erhao\heiti\@subtitle\\
```
并且大标题如果只有一行。latex输出的pdf会发现这一行整体不在居中，而是中间靠上方的位置。示意图如下：
![图片](https://user-images.githubusercontent.com/17799955/111054943-a526f580-84ab-11eb-839b-130ff0bfe1c0.png)

**Comment by gengdd** [comment]
你好！请问每章页眉的问题解决了吗？还有模板里边英文文献是全大写，不应该是首字母大写的形式吗？

**Comment by jhhuang96** [comment]
@gengdd 每章页眉的问题感觉问题不是很大，知网也看到seu用latex模板没有每章页眉。 参考文献确实有问题，参看SEU学生手册，英文姓名应该是首字母大写，而不是全大写。需要与作者沟通修改了。

**Comment by gengdd** [comment]
@jhhuang96 我又查了一下，作者名全大写才是标准格式规定的，只是大家都不这么写，查到一个修改的方法。
https://ask.csdn.net/questions/1054501

**Comment by jhhuang96** [comment]
@gengdd 我测试了一下，把bst文件的474行：
```
{ "u" change.case$ }
```
改成
```
{ }
```
好像就没问题了。你也是这么更改的嘛？

**Comment by jhhuang96** [comment]
> 
> 
> 你好！请问每章页眉的问题解决了吗？

@gengdd  issue #2 评论区已经有解决方案了

**Comment by gengdd** [comment]
@jhhuang96 感谢！！！
