### ISSUE TITLE
请问subsubsection如何修改成4.1.1.1这种序号

### ISSUE THREAD

**Issue by SkyeLan** [wurahara/SEU-master-thesis#6]
subsubsection的标题能修改成 4.1.1.1 这样的序号吗？cls里面好像只能改字体，没有办法把序号给标出来

**Comment by wurahara** [comment]
由于《东南大学研究生学位论文格式规定》中只规定到三级标题的相关格式，我们认为在四级标题中添加序号是不合适的。这是因为四级标题的字号等于或者小于正文，添加序号会使得层次结构过于琐碎，且影响美观。
