### ISSUE TITLE
title中副标题为空编译不成功

### ISSUE THREAD

**Issue by li-Yongpeng** [wurahara/SEU-master-thesis#7]
在win10环境下，
`  \title
    {东南大学 \LaTeX 论文模板使用手册}                                      % Thesis Title
    {}                                          % Thesis Subtitle
    {Southeast University \LaTeX ~Thesis Template User Manual}  % Thesis English Title
    {}            % Thesis English Subtitle`
中英文副标题设置为空，编译不通过，\makebigcover命令不通过，报错信息为：

! LaTeX Error: There's no line here to end.
See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...
l.60 \makebigcover

**Comment by li-Yongpeng** [comment]
中文副标题设置为空，编译不通过，英文副标题可以为空能通过编译

**Comment by JuanJuanQingQuan** [comment]
> 在win10环境下， ` \title {东南大学 \LaTeX 论文模板使用手册} % Thesis Title {} % Thesis Subtitle {Southeast University \LaTeX ~Thesis Template User Manual} % Thesis English Title {} % Thesis English Subtitle` 中英文副标题设置为空，编译不通过，\makebigcover命令不通过，报错信息为：
> 
> ! LaTeX Error: There's no line here to end. See the LaTeX manual or LaTeX Companion for explanation. Type H for immediate help. ... l.60 \makebigcover
这里你点击回车，其实可以继续执行。我这边测试了下，把cls文件第500行注释掉就行了，估计是因为副标题为空导致这边图片放置有影响

**Comment by JuanJuanQingQuan** [comment]
![image](https://user-images.githubusercontent.com/31130047/154918258-9f7011b6-8e65-437e-ba79-289915324e47.png)
也可参考这个
